version: 2

jobs:
  build:
    docker:
      - image: kchawlapi/nilearn-circleci
    parallelism: 4
    environment:
      DISTRIB: "conda"
      PYTHON_VERSION: "3.6"
      NUMPY_VERSION: "*"
      SCIPY_VERSION: "*"
      SCIKIT_LEARN_VERSION: "*"
      MATPLOTLIB_VERSION: "*"

    steps:
      - checkout
      - restore_cache:
          key: v1-datasets-{{ .Branch }}
      - run:
          name: Running CircleCI test (make html)
          command: |
            source activate testenv
            pip install -e .
            set -o pipefail && cd doc && make html-strict 2>&1 | tee $HOME/log.txt
          no_output_timeout: 5h
      - save_cache:
          key: v1-packages+datasets-{{ .Branch }}
          paths:
          - $HOME/nilearn_data

      - store_artifacts:
          path: doc/_build/html
      - store_artifacts:
          path: coverage
      - store_artifacts:
          path: $HOME/log.txt
          destination: log.txt




